GET http://localhost:5172/

###
GET http://localhost:5172/games/1

###
POST http://localhost:5172/games
Content-Type: application/json

{
    "name": "Call of duty",
    "genreId": 1,
    "price": 59.99,
    "releaseDate": "2023-09-15"
}
###
PUT http://localhost:5172/games/4
Content-Type: application/json


{
    "name": "Call of duty mw3",
    "genreId": 1,
    "price": 59.99,
    "releaseDate": "2023-09-15"
}

###
DELETE http://localhost:5172/games/1
### 
GET http://localhost:5172/genres

